### ISSUE TITLE
Unable to generate output with XLingPaper text generated from FLEx project

### ISSUE THREAD

**Issue by TDavLinguist** [langsci/lsp-converters#1]
# Issues
The main issue is that there is no output after running the xlingpaper2langsci.py script in Python 3.5.2 (Linux Mint distro). Due to a lack of documentation, I looked briefly at the code (though, I am not proficient in Python scripting) and did not see any option for specifying an output file.

When I run the command in the terminal, python prints this message:
`$ python3 xlingpaper2langsci.py bur_xling_test.xml`
`%% converted from bur_xling_test.xml`

I look in the directory, and there appears to be no output file, only the original `bur_xling_test.xml` document that I generated from FLEx (attached in ZIP) [bur_xling_test.xml.zip](https://github.com/langsci/conversion/files/3968563/bur_xling_test.xml.zip).

# Reason for interest in this converter
While I don't have any current plans to submit a manuscript to LangSci, I was hoping that there would be a tool like this to automatically convert FLEx text data into TeX markup. So, I wanted to test it out with a sample document, to see if it would actually work. Not only did it not work, I didn't even get a corrupted output file to try and tweak.

# Steps to re-create

1. Export Interlinear from FLEx as "XLingPaper, as examples, align words"
2. Download xlingpaper2langsci.py from RAW GitHub source
3. Run code in Python 3.5.2 from Linux terminal, specifying `bur_xling_test.xml` as first argument of the command.

Thanks for any input!

**Comment by TDavLinguist** [comment]
One thing I've realized is xlingpaper2langsci.py only appears to work when the text is generated with the "XLingPaper, align words" option and **not** with the "as examples" option. So, I've generated another file [bur_xling_full_test.xml.zip](https://github.com/langsci/conversion/files/3968668/bur_xling_full_test.xml.zip) and when I ran it with the program, this was the output in the terminal [bur_xling_full_test_error.txt](https://github.com/langsci/conversion/files/3968683/bur_xling_full_test_error.txt).

As the last traceback mentioned `raise ValueError`, I looked at the source code in vim and found this:
**`if te.text == None:`**
`      return ''`
`    print(te,te.tag,te.text,te.tail,te.attrib)`
`    raise ValueError`
`    return te.text`
Does this mean that the script is not seeing the text in the generated file? That would be impossible, as there is nothing else in the XML besides the small interlinear portion that I exported.

Thank you, again.

**Comment by Glottotopia** [comment]
your XML files have `<wrd>`, which was not found in the ones I used for developing. I have now adapted the code. 

You also need to change `<section1>` to `<chapter>`. 

The `bur_xling_test.xml` file should work then. The `bur_xling_full_test.xml` will require you to remove `<interlinear-text>` and to add `<example> ... </example>` around `<interlinear>...</interlinear>`

**Comment by TDavLinguist** [comment]
> your XML files have `<wrd>`, which was not found in the ones I used for developing. I have now adapted the code.
> 
> You also need to change `<section1>` to `<chapter>`.
> 
> The `bur_xling_test.xml` file should work then. The `bur_xling_full_test.xml` will require you to remove `<interlinear-text>` and to add `<example> ... </example>` around `<interlinear>...</interlinear>`

It works like a charm! Thank you, Sebastian! I'll close the issue, now.
